apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: mayureshkosandar/customer:0.2
          ports:
            - containerPort: 8185

---

apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
#  type: LoadBalancer
  selector:
    app: customer
  ports:
    - port: 8185
      targetPort: 8185
      protocol: TCP
